/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.biblioteca;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JPopupMenu;
import javax.swing.JMenuItem;

/**
 *
 * Tela responsável pelo módulo de Empréstimos do sistema.
 * Permite registrar empréstimos e devoluções, com autocompletar de
 * nomes de usuários e títulos de livros, além de listar todos os
 * empréstimos existentes numa tabela.
 *
 * @author Usuario
 */
public class TelaEmprestimos extends javax.swing.JFrame {

    /**
     * Creates new form TelaEmprestimos
     */
    public TelaEmprestimos() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        carregarEmprestimos();
        
        ativarAutocompletar(campoUsuarioId, "usuarios", "nome");
        ativarAutocompletar(campoLivroId, "livros", "titulo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTabelaEmprestimos = new javax.swing.JScrollPane();
        tabelaEmprestimos = new javax.swing.JTable();
        lblUsuarioNome = new javax.swing.JLabel();
        lblLivroNome = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        campoUsuarioId = new javax.swing.JTextField();
        campoLivroId = new javax.swing.JTextField();
        btnDevolver = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaEmprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Usuário", "Livro", "Data Empréstimo", "Data Devolução", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        painelTabelaEmprestimos.setViewportView(tabelaEmprestimos);

        lblUsuarioNome.setText("Nome do Usuário:");

        lblLivroNome.setText("Nome do Livro:");

        btnRegistrar.setText("Registrar Empréstimo");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnDevolver.setText("Registrar Devolução");
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar Lista");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblUsuarioNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoUsuarioId, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLivroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoLivroId, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelTabelaEmprestimos)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btnDevolver)
                        .addGap(18, 18, 18)
                        .addComponent(btnAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnFechar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioNome)
                    .addComponent(lblLivroNome)
                    .addComponent(btnRegistrar)
                    .addComponent(campoUsuarioId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoLivroId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelTabelaEmprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDevolver)
                    .addComponent(btnAtualizar)
                    .addComponent(btnFechar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Registra um novo empréstimo a partir do nome do usuário e do
     * título do livro digitados nos campos.
     * A consulta usa subselects com ILIKE para localizar os IDs
     * correspondentes; o INSERT só ocorre se ambos existirem,evitando
     * registrar um empréstimo com usuário ou livro inválido.
     */
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String nomeUsuario = campoUsuarioId.getText().trim();
        String tituloLivro = campoLivroId.getText().trim();

        if (nomeUsuario.isEmpty() || tituloLivro.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o Nome do Usuário e o Titulo do Livro.");
            return;
        }

        Connection conn = Biblioteca.conectar();
        if (conn == null) return;

        String sql = "INSERT INTO emprestimos "
            + "(usuario_id, livro_id, data_emprestimo, status) "
            + "SELECT "
            + "(SELECT id FROM usuarios WHERE nome ILIKE ? LIMIT 1), "
            + "(SELECT id FROM livros WHERE titulo ILIKE ? LIMIT 1), "
            + "CURRENT_DATE, 'EM ANDAMENTO' "
            + "WHERE EXISTS (SELECT 1 FROM usuarios WHERE nome ILIKE ?) "
            + "AND EXISTS (SELECT 1 FROM livros WHERE titulo ILIKE ?)"; 

        try (conn; PreparedStatement stmt = conn.prepareStatement(sql)) {
            String buscaUsuario = "%" + nomeUsuario + "%";
            String buscaLivro = "%" + tituloLivro + "%";
            
            stmt.setString(1, nomeUsuario);
            stmt.setString(2, tituloLivro);
            stmt.setString(3, nomeUsuario);
            stmt.setString(4, tituloLivro);
            
            int registrosInseridos = stmt.executeUpdate();
            
            if (registrosInseridos == 0) {
                JOptionPane.showMessageDialog(this, "Usuário ou livro não encontrado.");
                return;
            }
            
            JOptionPane.showMessageDialog(this, "Empréstimo registrado com sucesso!");
            
            campoUsuarioId.setText("");
            campoLivroId.setText("");
            carregarEmprestimos();  
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao registrar empréstimo: " + e.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed
    
    /**
    * Busca até 8 nomes/títulos que contenham o texto digitado.
    * Usado para exibir sugestões enquanto o usuário digita.
    */
    private List<String> buscarSugestoes(String tabela, String coluna, String termo) {
        List<String> sugestoes = new ArrayList<>();
        if (termo.isEmpty()) return sugestoes;

        Connection conn = Biblioteca.conectar();
        if (conn == null) return sugestoes;

        String sql = "SELECT " + coluna + " FROM " + tabela + " WHERE " + coluna
                + " ILIKE ? ORDER BY " + coluna + " LIMIT 8";

        try (conn; PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, "%" + termo + "%");
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                sugestoes.add(rs.getString(coluna));
            }
        } catch (SQLException e) {
            System.out.println("Erro ao buscar sugestões: " + e.getMessage());
        }
        return sugestoes;
    }

    /**
    * Liga um campo de texto a um menu suspenso de sugestões, consultando
    * a tabela/coluna informadas a cada caractere digitado.
    */
    private void ativarAutocompletar(javax.swing.JTextField campo, String tabela, String coluna) {
        JPopupMenu popup = new JPopupMenu();

        campo.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            private void atualizarSugestoes() {
                String texto = campo.getText().trim();
                popup.removeAll();

                List<String> sugestoes = buscarSugestoes(tabela, coluna, texto);
                if (sugestoes.isEmpty()) {
                    popup.setVisible(false);
                    return;
                }

                for (String sugestao : sugestoes) {
                    JMenuItem item = new JMenuItem(sugestao);
                    item.addActionListener(e -> {
                        campo.setText(sugestao);
                        popup.setVisible(false);
                    });
                    popup.add(item);
                }

                popup.show(campo, 0, campo.getHeight());
            }

            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) { atualizarSugestoes(); }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) { atualizarSugestoes(); }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) { }
        });
    }
    
    /**
     * Registra a devolução do empréstimo selecionado na tabela,
     * marcando a data de devolução como a data atual e o status
     * como "DEVOLVIDO". Impede registrar devolução duplicada.
     */
    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        int linha = tabelaEmprestimos.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um empréstimo na tabela.");
            return;
        }

        int id = (int) tabelaEmprestimos.getValueAt(linha, 0);
        String statusAtual = (String) tabelaEmprestimos.getValueAt(linha, 5);

        if ("DEVOLVIDO".equalsIgnoreCase(statusAtual)) {
            JOptionPane.showMessageDialog(this, "Este empréstimo já foi devolvido.");
            return;
        }

        Connection conn = Biblioteca.conectar();
        if (conn == null) return;

        String sql = "UPDATE emprestimos SET data_devolucao = CURRENT_DATE, status = 'DEVOLVIDO' WHERE id = ?";

        try (conn; PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setInt(1, id);
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Devolução registrada com sucesso!");
            carregarEmprestimos();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao registrar devolução: " + e.getMessage());
        }
    }//GEN-LAST:event_btnDevolverActionPerformed
    
    /**
     * Recarrega a tabela de empréstimos com os dados mais recentes do banco.
     */
    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        carregarEmprestimos();
    }//GEN-LAST:event_btnAtualizarActionPerformed
    
    /**
     * Fecha esta janela sem encerrar o restante da aplicação.
     */
    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed
    
    /**
    * Recarrega a tabela de empréstimos com os dados atuais do banco.
    * Limpa as linhas existentes antes de repopular, para evitar duplicar
    * registros quando chamado depois de um cadastro/devolução.
    * Faz JOIN com usuarios e livros para exibir nome/título em vez dos IDs.
    */
    private void carregarEmprestimos() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaEmprestimos.getModel();
        modelo.setRowCount(0);

        Connection conn = Biblioteca.conectar();
        if (conn == null) return;

        String sql = "SELECT e.id, u.nome AS usuario, l.titulo AS livro, "
                + "e.data_emprestimo, e.data_devolucao, e.status "
                + "FROM emprestimos e "
                + "JOIN usuarios u ON u.id = e.usuario_id "
                + "JOIN livros l ON l.id = e.livro_id "
                + "ORDER BY e.id";

        try (conn; PreparedStatement stmt = conn.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("usuario"),
                    rs.getString("livro"),
                    rs.getDate("data_emprestimo"),
                    rs.getDate("data_devolucao"),
                    rs.getString("status")
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao listar empréstimos: " + e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEmprestimos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JTextField campoLivroId;
    private javax.swing.JTextField campoUsuarioId;
    private javax.swing.JLabel lblLivroNome;
    private javax.swing.JLabel lblUsuarioNome;
    private javax.swing.JScrollPane painelTabelaEmprestimos;
    private javax.swing.JTable tabelaEmprestimos;
    // End of variables declaration//GEN-END:variables
}
